#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: 2017-02-21
###############################################################################

#source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/utils"


function create_new_config() {

cat > "$1" <<_EOF_
#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: $(whoami)
# Updated: $(date)
###############################################################################

# TODO: add your configurations below
project="$2"
app="$3"
image_stream="s2i-java"
timezone="Asia/Shanghai"
profile="dev"
port="${port}"
group_id=cn.vpclub.moses
artifact_id=${app}

_EOF_

log_debug "$2/$3"
}

function init_app() {
  new_workspace="$1"
  project_name="$2"
  app_name="$3"
  mkdir -p "${new_workspace}"
  pushd "${new_workspace}" > /dev/null
  create_new_config "${new_workspace}/hi.conf" "${project_name}" "${app_name}"

  if [ ! -d ".git" ] && [ $(which git | grep git | wc -l) == 1 ]; then
    git init
  fi

  popd > /dev/null  
}

function run() {
  result=1
  new_workspace="${PWD}"
  if [ "${new_app}" != "" ]; then
    new_workspace="${PWD}/${new_app}"
  fi

  get_dir_from_path project_name "${new_workspace}"
  get_folder_from_path project_name "${project_name}"
  log_debug "project_name: ${project_name}"

  get_folder_from_path app_name "${new_workspace}"
  log_debug "app_name: ${app_name}"

  log_debug "port: ${port}"
  if [ "${port}" == "" ]; then
    port=8080
  fi
  log_debug "port: ${port}"
  
  if [ -f "${new_workspace}/hi.conf" ]; then
    if prompt_yesorno "${app_name} is already exist, do you wish to overwrie it? [yes/no]"; then
      init_app "${new_workspace}" "${project_name}" "${app_name}"
    fi
  else
    init_app "${new_workspace}" "${project_name}" "${app_name}"
  fi

  result=$?

  eval  $1='"$result"' 
  eval  $2='"$cli"' 
}
