#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Mon Mar 27 23:24:29 CST 2017
# Module: oc
# Submodule: 
# Command: deploy
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function delete() {
  # deploy(project, app, ver, "dev", "Asia/Shanghai")
  ver=$(get_version)
  project_domain="${project}-${domain}"
  imageTag="latest"
  log_debug "deploy: ${project}/${app}, ${ver}, ${project_domain}, ${timezone} ${port}"
  
}

function run() {
  cli="delete"

  resource=${arg3}
  if [ "${resource}" == "all" ]; then
    resource=po,svc,routes,rc,dc,is,builds,bc
  fi

  log_debug "resource: ${resource}"

  oc delete ${resource} -l app=${app}

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
