#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Mon Mar 27 23:24:29 CST 2017
# Module: oc
# Submodule: 
# Command: deploy
###############################################################################
parser="${HI_CLI_HOME}/utils/parser.py"
###############################################################################

function get_apis() {
  
  log_debug "get apis"

  apis=$(http http://kong-admin-kong-gateway-dev.apps.vpclub.io/apis)

  value=$(python "${parser}" json "${apis}" data )
  log_debug "api: ${value}"
  
}

function run() {
  cli="get apis"

  get_apis

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
