#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Mon Mar 27 23:24:29 CST 2017
# Module: oc
# Submodule: 
# Command: common util
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function get_java_app_version() {
  echo $(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)')
}
###############################################################################
function get_nodejs_app_version() {
  echo $(node -p "require('./package.json').version")
}
###############################################################################
function is_exist() {
  resource=$1
  app=$2
  project_profile=$3

  if [ $(oc get "${resource}" -n ${project_profile} | grep ${app} | awk '{print $1}' | grep -v "\-${app}" | grep -v "${app}\-" | wc -l) == 0 ]; then
    echo "no"
  else
    echo "yes"
  fi
}
###############################################################################
function is_oc_logged_in() {
  oc whoami 2>/dev/null
  [ $? == 0 ] && echo "yes" || echo "no"
}

###############################################################################
function ensure_oc_login() {
  oc whoami 2>/dev/null
  if [ $? != 0 ]; then
    oc login
  fi
}
###############################################################################
