#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu May 18 18:56:35 CST 2017
# Module: cicd
# Submodule: 
# Command: create
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function run() {
  new_project=${arg4}
  profiles_selection="dev test stage prod"
  if [[ "${profiles_selection}" =~ .*${arg5}.* ]]; then
    new_project=${arg4}-${arg5}
  fi

  log_debug "oc new-project ${new_project}"
  log_debug "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n ${new_project}"
  log_debug "oc policy add-role-to-user edit system:serviceaccount:cicd:default -n ${new_project}"

  log_debug "oc adm policy add-scc-to-user anyuid system:serviceaccount:${new_project}:default"

  log_debug "arg1: $arg1"
  log_debug "arg2: $arg2"
  log_debug "arg3: $arg3"
  log_debug "arg4: $arg4"
  log_debug "arg5: $arg5"
  log_debug "profiles: $profiles"
  
  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
