#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Sat Mar 18 15:33:39 CST 2017
# module: oc
# Action: login
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function run() {
  cli="create new user"

  cd /etc/origin/master
  htpasswd -b /etc/origin/master/htpasswd ${user} ${password}

  if [ "${project}" != "" ] && [ "${role}" != "" ]; 
  then
    oadm policy add-role-to-user ${role} johnd -n ${project}
  fi

  result=$?

  eval $1=\${result}
  eval $2=\${cli}
}

###############################################################################


